### ISSUE TITLE
Task(Heroku): implementação do serviço de hospedagem do banco de dados

### ISSUE THREAD

**Issue by Potatoyz908** [unb-mds/2024-2-AcheiUnB#107]
## Descrição

Esta tarefa tem como objetivo implementar e hospedar o banco de dados no Heroku, garantindo que a aplicação AcheiUnB tenha uma base de dados funcional e acessível para o armazenamento e gerenciamento de informações.

## Tarefas

- [x] Criar o banco de dados no Heroku utilizando a ferramenta de provisionamento do Heroku (como o Heroku Postgres).
- [x] Configurar as credenciais de acesso do banco de dados no ambiente da aplicação.
- [x] Implementar a lógica de conexão entre o back-end da aplicação e o banco de dados.
- [x] Testar a integração para garantir que a aplicação esteja se comunicando corretamente com o banco de dados.
- [x] Garantir que as variáveis de ambiente necessárias (como a URL de conexão) estejam configuradas corretamente no Heroku.
- [x] Documentar o processo de implementação do banco de dados no Heroku no repositório do projeto.
- [x] Testar o funcionamento do banco de dados no ambiente de produção para garantir que todas as operações estejam funcionando conforme esperado.

**Comment by 314dro** [comment]
Ótimo trabalho, Euller!!
