### ISSUE TITLE
Task(Cadastro): Ajuste no cadastro de Item 

### ISSUE THREAD

**Issue by Potatoyz908** [unb-mds/2024-2-AcheiUnB#109]
## Descrição

Descreva o objetivo da tarefa de forma clara e objetiva.

## Tarefas

- [x] Defina a primeira subtarefa ou ação.
- [x] Inclua mais subtarefas se necessário.
- [x] Certifique-se de que todos os itens foram concluídos antes de finalizar a issue.

**Comment by 314dro** [comment]
Muito bem!
