### ISSUE TITLE
Rabbit(Estudo): Introdução ao Django Channels, Celery e Redis

### ISSUE THREAD

**Issue by Potatoyz908** [unb-mds/2024-2-AcheiUnB#11]
### O que é?

O **Django Channels** é uma extensão do Django que permite a comunicação em tempo real e a gestão de conexões assíncronas, superando as limitações do Django tradicional nesse aspecto. Juntamente com **Celery**, que é uma ferramenta para gerenciamento de tarefas assíncronas, e **Redis**, que atua como um broker de mensagens, essas tecnologias formam uma poderosa stack para desenvolver aplicações web modernas e responsivas.

### Como funciona?

O Django Channels utiliza o protocolo WebSocket para permitir a comunicação bidirecional entre o cliente e o servidor, o que é ideal para aplicações que requerem atualização em tempo real, como chats e notificações. O Celery permite que tarefas pesadas sejam executadas em segundo plano, liberando o servidor para atender outras requisições. O Redis serve como um sistema de mensagens em memória, gerenciando as filas de tarefas do Celery e as conexões do Django Channels.

### Quem será o coelho?

Euller, @Potatoyz908, será o responsável por esses conceitos.

### Tópicos a serem estudados:

- [x] Introdução ao Django Channels
- [x] Configuração do Django Channels
- [x] Integração do Celery com Django
- [x] Configuração do Redis como broker para Celery
- [x] Criação e uso de signals no Django
- [x] Automatização de notificações com signals

### Estudo:

Todas as anotações dos estudos estão na pasta [Coelhos](https://github.com/unb-mds/2024-2-AcheiUnB/blob/main/Coelhos/Rabbit(Estudo)%3A%20Introdu%C3%A7%C3%A3o%20ao%20Django%20Channels%2C%20Celery%20e%20Redis.md).

**Comment by Potatoyz908** [comment]
Estudo finalizado!

**Comment by leoramiroo** [comment]
Mais um estudo finalizado, Ótimo trabalho!!
