### ISSUE TITLE
Task(Ruff): Implementar Ruff para Linting e Formatação de Código

### ISSUE THREAD

**Issue by Potatoyz908** [unb-mds/2024-2-AcheiUnB#120]
## **Descrição**

Implementar o **Ruff** como ferramenta de linting e formatação de código no projeto. O Ruff será configurado para corrigir automaticamente problemas de formatação e linting, garantindo um código consistente e alinhado aos padrões definidos no projeto. A integração será feita no ambiente Docker e no script `entrypoint.sh`.

---

## **Tarefas**

- [x] Adicionar o Ruff ao arquivo `requirements.txt` do projeto.
- [x] Atualizar o `pyproject.toml` com as configurações do Ruff:
  - Limite de linha (`line-length`) ajustado para 88 caracteres.
  - Exclusão de diretórios irrelevantes como `migrations` e `__pycache__`.
  - Ativação de verificações de linting específicas (`select`).
- [x] Atualizar o `Dockerfile` para instalar o Ruff no ambiente Docker.
- [x] Configurar o `entrypoint.sh` para:
  - Executar o Ruff antes de qualquer operação com o banco de dados.
  - Corrigir automaticamente problemas encontrados.
- [x] Garantir que o Ruff seja executado sempre que o contêiner for iniciado.
- [x] Testar a execução do Ruff manualmente no contêiner:
  - Comando: `docker compose run web ruff . --fix`.
- [x] Documentar o processo no repositório para que os desenvolvedores saibam como usar o Ruff.

---

## **Critérios de Aceitação**

- [x] O Ruff deve corrigir automaticamente problemas de linting e formatação.
- [x] O Ruff não deve interferir na execução do projeto (ex.: erros relacionados ao banco de dados).
- [x] Configuração do Ruff deve estar claramente documentada no repositório.
- [x] Comando para executar o Ruff manualmente no Docker deve funcionar sem erros.

**Comment by 314dro** [comment]
Muito bem!
