### ISSUE TITLE
Rabbit(Estudo): APIs para backend

### ISSUE THREAD

**Issue by 314dro** [unb-mds/2024-2-AcheiUnB#13]
## APIs para backend do projeto

**O que é?**
Nesta issue foi proposto se pesquisar sobre APIs e bibliotecar que seriam utilizadas no nosso projeto com a intenção de descobrir as melhores tecnologias que atenderiam os requisitos da nossa aplicação. A API (Application Programming Interface) é um conjunto de regras e definições que tem como função intermediar a comunicação universal entre diferentes sistemas Em outras palavras, é uma interface que possibilita que um sistema utilize funcionalidades de outro sistema sem precisar entender sua implementação interna.
Em software, uma biblioteca é um conjunto de funções, classes e rotinas pré-escritas que podem ser reutilizadas em diferentes programas para facilitar o desenvolvimento.

**Como funciona?**
As APIs facilitam a comunicação entre um cliente (como um aplicativo ou navegador) e um servidor que fornece recursos ou serviços. Essa comunicação é geralmente feita através de requisições e respostas.
Bibliotecas são organizadas em módulos ou pacotes que fornecem funcionalidades específicas, como manipulação de dados, operações matemáticas, comunicação com redes, manipulação de arquivos e muito mais.

**Quem será o coelho?**
O coelho Pedro Silva, @314dro, foi responsável por esse estudo.

**Tópicos a serem estudados:**

- [x] Allauth
- [x] Oauth2
- [x] Django Forms, Message.
- [x] Pillow
- [x] Django Filter

**Estudo:**
Todas as anotações dos estudos estão na pasta [Coelhos](https://github.com/unb-mds/2024-2-AcheiUnB/tree/main/Coelhos).

**Comment by Potatoyz908** [comment]
Bom trabalho!
