### ISSUE TITLE
Rabbit(Estudo): Django Rest Framework (DRF)

### ISSUE THREAD

**Issue by 314dro** [unb-mds/2024-2-AcheiUnB#14]
## Nome do conceito ou tecnologia

**O que é?**
O Django REST Framework (DRF) é uma biblioteca poderosa e flexível, construída sobre o Django, que facilita a criação de APIs Web RESTful. Ele oferece ferramentas para desenvolvedores construírem APIs robustas e escaláveis para suas aplicações.

**Como funciona?**
O Django REST Framework (DRF) funciona por meio de uma padronização REST na criação de novas APIs, permitindo assim a comunicação no protocolo HTTP entre o código e a API desejada. Além de se utilizar do métodos de serialização para converter dados complexos em formatos facilmente compartilháveis pelo sistema, como Json.

**Quem será o coelho?**
O coelho Pedro Silva, @314dro, apresentará o estudo.

**Tópicos a serem estudados:**

- [x] API
- [x] Rest
- [x] Métodos HTTP
- [x] Serialização
- [x] Segurança

**Estudo:**
Todas as anotações dos estudos estão em [Django Rest Framework](https://github.com/unb-mds/2024-2-AcheiUnB/blob/main/Coelhos/Rabbit(Estudo)%3A%20Django%20Rest%20Framework.md).

**Comment by Potatoyz908** [comment]
Opa, Pedro! Excelente trabalho, no entanto, parece que existe um erro de formatação em sua descrição, peço que dê uma olhada nisso antes de finalizarmos.

**Comment by 314dro** [comment]
Muito obrigado pelo feedback, Euller! Concertarei esse erro agora.

**Comment by Davicamilo23** [comment]
Mais um estudo realizado com sucesso, parabéns!
