### ISSUE TITLE
Task(Docs): Realização do Protótipo de Arquitetura

### ISSUE THREAD

**Issue by Potatoyz908** [unb-mds/2024-2-AcheiUnB#17]
#### Descrição

O objetivo desta tarefa é elaborar um protótipo de arquitetura para o projeto, definindo a estrutura geral dos componentes de software e suas interações. Esse protótipo servirá como uma base para orientar o desenvolvimento das funcionalidades, garantindo uma visão clara do sistema e a consistência entre as equipes de Front-end, Back-end e DevOps.

#### Tarefas

- [x] **Definir os Componentes Principais:** Identificar e documentar os principais módulos e serviços do sistema, como Front-end, Back-end, banco de dados, e ferramentas de DevOps.
- [x] **Desenhar o Diagrama de Arquitetura:** Elaborar um diagrama de alto nível representando os componentes e suas interações. Recomenda-se utilizar ferramentas como Lucidchart, Draw.io, ou Figma.
- [x] **Estabelecer a Comunicação entre Componentes:** Definir os métodos de comunicação entre os componentes principais.
- [ ] **Validar o Protótipo com a Equipe:** Apresentar o protótipo de arquitetura em uma reunião com os membros da equipe para feedback e possíveis ajustes.

**Protótipo**

Pode ser encontrado tanto na pasta Coelhos quanto no [Figma](https://www.figma.com/board/ai5E0akKD2yDr9FfnW9k4l/Prot%C3%B3tipo-de-Arquitetura?node-id=0-1&t=19ErTsypFap1Nvl9-1).

**Comment by 314dro** [comment]
@Potatoyz908 e @leoramiroo o livro que estava lendo sobre arquitetura de software deu ótimos exemplos de tipos diferentes de protótipos de arquitetura a partir da pg 165, https://archive.org/details/sommerville-engenharia-de-software-8a/page/164/mode/1up?view=theater&q=stack . Suguiro que deem uma olhada e estudem sebre 😁

**Comment by Potatoyz908** [comment]
Valeu pela indicação! Vamos dar uma olhada e nos aprofundar nos tipos de protótipos de arquitetura. Acredito que esses exemplos vão realmente agregar bastante ao projeto! Obrigado pela sugestão!
