### ISSUE TITLE
Task(Docs): Documentação para Padrões de Commit e Nomeação de Branches

### ISSUE THREAD

**Issue by 314dro** [unb-mds/2024-2-AcheiUnB#21]
#### Descrição

Este estudo descreve os padrões para mensagens de commit e para a nomeação de branches a serem seguidos no projeto. O objetivo é promover a consistência e a rastreabilidade no histórico de mudanças, facilitando o desenvolvimento colaborativo e o monitoramento das alterações. Para as mensagens de commit, será utilizado o padrão Conventional Commits. A nomeação de branches seguirá um formato específico, com cada commit e branch vinculado a uma issue para assegurar o controle de mudanças.

#### Tarefas

- [x] Definir estrutura das mensagens de commit
- [x] Definir tipos de commit e suas descrições 
- [x] Explicar as regras para vinculação de commits com issues 
- [x] Especificar padrão de nomeação de branches 
- [x] Definir tipos de branch e suas descrições

[Link para o estudo](https://github.com/unb-mds/2024-2-AcheiUnB/blob/docs/docs/Task(Docs)%3A%20Documenta%C3%A7%C3%A3o%20para%20Padr%C3%B5es%20de%20Commit%20e%20Nomea%C3%A7%C3%A3o%20de%20Branches.md)

**Comment by leoramiroo** [comment]
Ótimo trabalho no estudo da Documentação, será bem útil!!
