### ISSUE TITLE
Task(Front-end): Levantamento de identidade visual do projeto

### ISSUE THREAD

**Issue by anaelisaramos** [unb-mds/2024-2-AcheiUnB#23]
## Descrição

Definir cores, fontes, logo e principais telas do projeto.

## Tarefas

- [x] Cores
- [x] Logo
- [x] Fontes
- [x] Principais telas
- [x] Slogan

[Acesse aqui](https://github.com/unb-mds/2024-2-AcheiUnB/blob/docs/docs/front-end/Visual-identity.md)

**Comment by anaelisaramos** [comment]
Finalizado, mas aberto a alterações 😊

**Comment by Potatoyz908** [comment]
Excelente trabalho, pessoal! 👏
