### ISSUE TITLE
Task(Front-end): Estudo aprofundado nas tecnologias do front

### ISSUE THREAD

**Issue by TiagoBalieiro** [unb-mds/2024-2-AcheiUnB#26]
## Descrição

Estudo aprofundado em Vue.js e Tailwind CSS, através de suas próprias documentações e vídeos.
Links úteis para estudo posterior:
- https://vuejs.org/guide/introduction.html 
- https://vueschool.io/courses/vue-js-fundamentals-with-the-composition-api 
- https://www.youtube.com/watch?v=cSa-SMVMGsE
- https://tailwindcss.com/docs/installation

## Tarefas

- [x] Estudo de Vue.js
- [x] Estudo de Tailwind CSS
- [x] Criação do projeto no Figma

**Comment by anaelisaramos** [comment]
Tooop ✨

**Comment by Davicamilo23** [comment]
Ótimo trabalho, pessoal!
