### ISSUE TITLE
Task(Back-end): Configuração do banco de dados e implementação dos usuários registrados em nosso sistema

### ISSUE THREAD

**Issue by 314dro** [unb-mds/2024-2-AcheiUnB#31]
## Descrição

Configurar o banco de dados do sistema e implementar o modelo de usuários registrados, garantindo que dados essenciais, como autenticação, roles (papéis) e permissões, estejam definidos. O objetivo é estabelecer a estrutura de usuários no banco de dados, permitindo operações básicas de registro, login e consulta.

## Tarefas

- [x] Configurar o banco de dados (PostgreSQL) para o projeto, garantindo conexão e acesso ao back-end.
- [x] Definir e implementar o modelo de usuário no banco de dados com campos essenciais (nome, email, senha, etc.).
- [x] Testar a criação, login e consulta de usuários, verificando se todas as operações funcionam conforme esperado.
- [x] Documentar o processo e configurações realizadas para facilitar futuras manutenções e atualizações.

**Comment by Potatoyz908** [comment]
Finalizado!
