### ISSUE TITLE
Task(DevOps): Revisar Docker e Kubernetes, melhorar a implementação do Docker e avaliar a possibilidade de implementação do Kubernetes no projeto

### ISSUE THREAD

**Issue by leoramiroo** [unb-mds/2024-2-AcheiUnB#36]
## Descrição

Melhorar a pesquisa sobre Docker e Kubernetes, fazer os updates necessários na Dockerização do projeto e avaliar a necessidade de implementação do Kubernetes no projeto.

## Tarefas

- [x] Revisar Docker e Kubernetes.
- [x] Melhorar a implementação do Docker.
- [x] Avaliar a possibilidade de implementação do Kubernetes no projeto.

**Comment by Davicamilo23** [comment]
Considerando que, para aplicações simples e em pequena escala, a complexidade do Kubernetes pode ser excessiva, havendo a possibilidade de soluções mais leves como Docker Swarm ou mesmo uma implantação simples em VMs, foi descartada a ideia de implementar o Kubernetes nesse projeto.
