### ISSUE TITLE
Rabbit(Estudo): Tecnologias Back-end

### ISSUE THREAD

**Issue by Potatoyz908** [unb-mds/2024-2-AcheiUnB#4]
### **Estudos sobre tecnologias Back-end**
---
#### **O que é?**
As tecnologias backend referem-se ao conjunto de ferramentas, linguagens de programação, frameworks e sistemas utilizados para construir, manter e escalar a infraestrutura e a lógica que sustentam uma aplicação do lado do servidor. Esse "lado servidor" é responsável por processar e responder às requisições feitas pelo usuário (lado cliente), gerenciando dados, autenticação, permissões de acesso, entre outros.

#### **Como funciona?**
Os coelhos produzirão um estudo sobre as tecnologias que podem servir para o desenvolvimento do Back-end do nosso projeto, incluindo frameworks para Python, bibliotecas Python e banco de dados. Servindo para delimitar o escopo do projeto.

#### **Quem serão os Coelhos?**
Os responsáveis por apresentar a discussão serão Euller Júlio, @Potatoyz908 , e Pedro Henrique, @314dro .

#### **Tópicos a serem estudados:**
- [x] **DBeaver**
- [x] **Django**
- [x] **PostgreSQL**
- [x] **Django Rest**
- [x] **API's**

#### **Notion de Estudo:**
[**Clique aqui**]() para acessar o Notion com os materiais de estudo e referências.

**Comment by anaelisaramos** [comment]
🎉🎉🎉
