### ISSUE TITLE
Task(front-end): Implementação inicial do protótipo de alta fidelidade

### ISSUE THREAD

**Issue by anaelisaramos** [unb-mds/2024-2-AcheiUnB#41]
## Implementação inicial do protótipo de alta fidelidade

Criação do protótipo de alta fidelidade, com transições e responsividade, no Figma

## Tarefas

- [x] Criação do projeto 
- [x] Pesquisar e importar um plug-in de Tailwind 
- [x] Planejamento e divisão das páginas
- [x] Ideia inicial

**Comment by anaelisaramos** [comment]
Evolução dessa issue [aqui](https://github.com/unb-mds/2024-2-AcheiUnB/tree/feat/add-figma-docs-v1/docs/front-end)

**Comment by Potatoyz908** [comment]
Está tudo pronto, pessoal?
