### ISSUE TITLE
Task(Back-end): Implementar suporte ao upload de imagens

### ISSUE THREAD

**Issue by Potatoyz908** [unb-mds/2024-2-AcheiUnB#56]
## Descrição

Habilitar o upload de imagens para o campo `image` do modelo `Item`.

## Tarefas

- [x] Configurar o campo ImageField no modelo Item para aceitar uploads.
- [x] Configurar MEDIA_URL e MEDIA_ROOT no settings.py para armazenar as imagens.
- [x] Testar upload de imagens via Postman utilizando o formato multipart/form-data.

**Comment by Potatoyz908** [comment]
Finalizado!

**Comment by 314dro** [comment]
Muito bem!
