### ISSUE TITLE
Task(Back-end): Configurar autenticação com JWT

### ISSUE THREAD

**Issue by Potatoyz908** [unb-mds/2024-2-AcheiUnB#57]
## Descrição

Proteger os endpoints sensíveis usando autenticação baseada em tokens JWT.

## Tarefas

- [x]  Configurar o DRF SimpleJWT no projeto.
- [x] Atualizar settings.py para usar DEFAULT_AUTHENTICATION_CLASSES.
- [x] Testar autenticação via endpoint de login para gerar tokens JWT.
- [x] Garantir que apenas usuários autenticados possam criar itens.

**Comment by Potatoyz908** [comment]
Finalizado!

**Comment by 314dro** [comment]
👏🏼👏🏼👏🏼
