### ISSUE TITLE
Rabbit(Estudo): Tecnologias Front-End

### ISSUE THREAD

**Issue by TiagoBalieiro** [unb-mds/2024-2-AcheiUnB#6]
## Estudos Front-End

**O que é?**
O front-end é a parte visual e interativa de uma aplicação ou site com a qual o usuário interage diretamente. Ferramentas e bibliotecas, como React e Bootstrap, ajudam a construir interfaces de maneira mais rápida e organizada. O principal foco do front-end é proporcionar uma experiência de uso agradável e intuitiva, cuidando do design e da usabilidade.

**Como funciona?**
O front-end é construído usando 3 principais tecnologias: HTML, CSS e JavaScript.  Ferramentas como frameworks e bibliotecas (React, Angular, Bootstrap) ajudam a organizar e acelerar o desenvolvimento de interfaces, garantindo uma experiência de usuário eficiente e agradável.

**Quem será o coelho?**
Os responsáveis por apresentar a por esta tarefa serão Ana Elisa, @anaelisaramos  e Tiago Balieiro, @TiagoBalieiro

**Tópicos a serem estudados:**

- [x] Figma
- [x] Bibliotecas CSS
- [x] Frameworks
- [x] Prettier

**Notion de estudo:**
[Clique aqui](https://github.com/unb-mds/2024-2AcheiUnB/blob/main/Coelhos/Rabbit(Estudo)%3A%20Tecnologias%20front-end.md) para acessar o Notion com os materiais de estudo e referências.

**Comment by Potatoyz908** [comment]
Ótimo trabalho, equipe. Antes de encerrarmos, sugiro que façamos alguns ajustes, pois a professora recomendou que utilizemos uma pasta em nosso repositório para armazenar nossos estudos, em substituição ao Notion, que temos adotado até o momento. Recomendo que sigamos o [novo template](https://github.com/unb-mds/2024-2-AcheiUnB/blob/main/.github/ISSUE_TEMPLATE/rabbit.md), já adaptado com as alterações recentes.

**Comment by 314dro** [comment]
Ótima pesquisa, Galera!!! Mas percebi que no documento dos Coelhos, na main, as imagens não estão aparecendo no estudo. Poderiam da uma olhada nisso?

**Comment by 314dro** [comment]
Ótimo trabalho!
