### ISSUE TITLE
rabbit(Django): Estudo sobre o framework Django

### ISSUE THREAD

**Issue by Potatoyz908** [unb-mds/2024-2-AcheiUnB#8]
## Django

**O que é?**
O Django é um framework web Python de código aberto, que se destaca por oferecer um ambiente que simplifica a criação de soluções web escaláveis, ao mesmo tempo, em que promove o desenvolvimento rápido e um design limpo, proporcionando ferramentas robustas e eficientes para pessoas desenvolvedoras.

**Como funciona?**
Django funciona como um framework robusto para desenvolvimento web, fornecendo um conjunto de ferramentas e abstrações que facilitam a criação de aplicações. Ele utiliza modelos (models) para definir a estrutura e os tipos de dados do aplicativo, permitindo a representação eficiente de tabelas e campos no banco de dados. As visualizações (views) são responsáveis por processar as solicitações HTTP dos usuários, conectando a lógica de negócios com a manipulação de dados, enquanto os templates definem a aparência das páginas web, permitindo a geração de HTML dinâmico.

**Quem será o coelho?**
Euller, @Potatoyz908 .

**Tópicos a serem estudados:**

- [x] Introdução
- [x] Configuração do Ambiente Django
- [x] Estrutura de um Projeto Django
- [x] Criação e Configuração de Aplicativos
- [x] Modelos e ORM
- [x] Criação e Aplicação de Migrations
- [x] Views: Function-Based vs Class-Based
- [x] Manipulação de URLs e Roteamento
- [x] Templates e Django Template Language (DTL)

**Estudo:**
Todas as anotações dos estudos estão na pasta [Coelhos](https://github.com/unb-mds/2024-2-AcheiUnB/blob/main/Coelhos/rabbit(Django)%3A%20Estudo%20sobre%20o%20framework%20Django.md).

**Comment by Potatoyz908** [comment]
Mais um estudo foi finalizado com sucesso!

**Comment by leoramiroo** [comment]
Ótimo trabalho, mais um estudo concluído!
