### ISSUE TITLE
Rabbit(Estudo): PostgreSQL para Django

### ISSUE THREAD

**Issue by Potatoyz908** [unb-mds/2024-2-AcheiUnB#9]
## Configuração do PostgreSQL para Django

**O que é?**  
O PostgreSQL é um sistema gerenciador de banco de dados objeto-relacional, conhecido por sua robustez, flexibilidade e suporte a transações complexas. O Django é um framework web para desenvolvimento em Python que permite criar aplicações de forma rápida e eficiente. A configuração do PostgreSQL no Django permite que a aplicação utilize este banco de dados para armazenar e gerenciar dados.

**Como funciona?**  
A configuração envolve a criação de um banco de dados no PostgreSQL, a definição de um usuário para gerenciá-lo, e a configuração das credenciais no arquivo `settings.py` do projeto Django. O Django utiliza o ORM (Object-Relational Mapping) para interagir com o banco de dados, permitindo realizar operações de CRUD (Create, Read, Update, Delete) de maneira simplificada.

**Quem será o coelho?**  
Euller Júlio, @Potatoyz908,  será o coelho responsável por estudar a configuração do PostgreSQL no Django e suas práticas recomendadas para otimização de consultas.

**Tópicos a serem estudados:**

- [x] Acesso e criação de banco de dados no PostgreSQL
- [x] Configuração de usuário e permissões no PostgreSQL
- [x] Configuração do Django para utilizar PostgreSQL
- [x] Uso de `select_related` e `prefetch_related` para otimização de consultas
- [x] Limitação de campos retornados com `only` e `defer`
- [x] Uso de filtros para reduzir a quantidade de dados
- [x] Contagem de resultados com `count()` em vez de `len()`
- [x] Anotações com `annotate` para operações de agregação
- [x] Indexação de campos no modelo
- [x] Evitar consultas N+1
- [x] Execução de consultas personalizadas com `raw` SQL
- [x] Utilização de `F` e `Q` para consultas complexas
- [x] Uso do DBeaver para gerenciamento do banco de dados

**Estudo:**  
Todas as anotações dos estudos estão na pasta [Coelhos](https://github.com/unb-mds/2024-2-AcheiUnB/blob/main/Coelhos/Rabbit(Estudo)%3A%20PostgreSQL%20para%20Django.md).

**Comment by 314dro** [comment]
Ótima pesquisa, Coelho!!
